version: '3.8'

services:
  voxel-slam:
    build: .
    container_name: voxel_slam_ros
    image: voxel_slam_ros:v2.0-rewrite
    tty: true
    stdin_open: true
    network_mode: host
    pid: "host" # 添加 pid 命名空间共享
    ipc: "host" # 添加 ipc 命名空间共享 
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # X11显示支持
      - ../:/workspace  # 挂载数据集目录
      - ./output:/output  # 挂载输出目录
    devices:
      - "/dev/dri:/dev/dri"  # GPU加速支持
    command: /bin/bash